blank_issues_enabled: false
contact_links:
  - name: BUG 反馈
    url: https://github.com/kongzue/DialogX/issues/new?assignees=&labels=&template=ISSUE_TEMPLATE_1.md
    about: 如果你有遇到 BUG 请选择此项进行反馈
  - name: 功能建议
    url: https://github.com/kongzue/DialogX/issues/new?assignees=&labels=&template=ISSUE_TEMPLATE_2.md
    about: 如果你希望 DialogX 增加新功能请选择此项
  - name: 申请加入 Powered By DialogX
    url: https://github.com/kongzue/DialogX/issues/new?assignees=&labels=&template=ISSUE_TEMPLATE_3.md
    about: 若您的应用正好在使用 DialogX 且愿意加入《Powered By DialogX》计划，请在此提交申请。